[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200